services:
  bakingbuddy:
    container_name: bakingbuddy
    image: bakingbuddy
    volumes:
      - /webapp/volume_data
    ports:
      - "23516:23516"
    build:
      context: ./
      dockerfile: Dockerfile
