services:
  bakingbuddy:
    container_name: bakingbuddy
    image: bakingbuddy
    volumes:
      - /wwwroot/assets
      - /wwwroot/files
      - Database/RecipeNotes.db
    ports:
      - "23516:23516"
    build:
      context: ./
      dockerfile: Dockerfile
